spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/pcenter'
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect